---
title: "Project1"
author: "Nicole Ashby"
date: "June 19, 2019"
output: word_document
---

  
```{r}
library(tidyverse)
library(GGally) 
```


```{r}
library(readr)
rain <- read_csv("rain.csv")

rain = rain %>% mutate(RainToday = as_factor(as.character(RainToday)))
rain = rain %>% mutate(RainTomorrow = as_factor(as.character(RainTomorrow)))

rain = rain %>% mutate(WindDir3pm = as_factor(as.character(WindDir3pm)))
rain = rain %>% mutate(WindGustDir = as_factor(as.character(WindGustDir)))
rain = rain %>% mutate(WindDir9am = as_factor(as.character(WindDir9am)))
```


 
```{r}
rain = rain %>% drop_na() 
str(rain)
summary(rain)
```


```{r}
ggplot(rain, aes(Humidity3pm, Cloud3pm, color=RainTomorrow)) +
  geom_point() +
  labs(title = "Rain Prediction (Humid,Clouds)", 
       x = "Humidity (percent) at 3pm", 
       y = "Fraction of sky obscured by cloud at 3pm" 
       )
```

The graph above shows us that with higher humidity and more clouds, there is a higher likelihood for rain tomorrow

```{r}
ggplot(rain, aes(Humidity3pm, RainToday, color=RainTomorrow)) +
  geom_point() +
  labs(title = "Rain Prediction (Humid,RainToday)", 
       x = "Humidity (percent) at 3pm",  
       y = "Precipitation (mm) in 24hr exceeds 1mm" 
       )
```

We can see from the graph above, that there is a greater chance of rain the next day if it rained today and if there is high humidity. 

```{r}
ggplot(rain, aes(Pressure3pm,Cloud3pm, color=RainTomorrow)) +
  geom_point() +
  labs(title = "Rain Prediction (Pressure,Clouds)", 
       x = "Atmospheric pressure (hpa) reduced to mean sea level at 3pm", 
       y = "Fraction of sky obscured by cloud at 3pm" 
       )
```

The graph above shows that if there is a combination of more clouds and low pressure, it is likely to rain tomorrow.

